### PR TITLE
rutor search added to MSX

### PR DESCRIPTION
**Pull request by damiva**
new MSX Plugin

### CODE REVIEW

**Review by damiva — COMMENTED** [review]
rutor search feature added to MSX plugin

**Comment by tsynik** [comment]
@damiva work in progress?
Conflicting files
server/web/msx/assets/russian.json.gz
server/web/msx/assets/tvx.js.gz
server/web/msx/msx.go

**Comment by damiva** [comment]
I really do not understand why there are conflicts and how to resolve them

**Comment by tsynik** [comment]
> I really do not understand why there are conflicts and how to resolve them

merged without rebase, please check current master on MSX

**Comment by tsynik** [comment]
@damiva

**Comment by tsynik** [comment]
это в apk эмулятора или сервере? "срисках" "уадио плеере"

**Comment by damiva** [comment]
Это опечатки в russian.json

пн, 20 февр. 2023 г., 00:20 nikk ***@***.***>:

**Comment by damiva** [comment]
Я поправил эти две ошибки (в пул реквесте).
Еще какие то недочеты пожелания есть?
Regards,
Mike


пн, 20 февр. 2023 г. в 07:20, Michael Damiva ***@***.***>:

**Pull request merged**
