### PR TITLE
Added Simplified Chinese translation

### PR DESCRIPTION
**Pull request by FaintGhost**

### CODE REVIEW

**Comment by YouROK** [comment]
Please add switch to set China

**Comment by FaintGhost** [comment]
Sorry for the oversight, it has been added.

**Comment by tbc0309** [comment]
#update Chinese translation [translation.zip](https://github.com/YouROK/TorrServer/files/11641826/translation.zip)

**Comment by FaintGhost** [comment]
> #update Chinese translation [translation.zip](https://github.com/YouROK/TorrServer/files/11641826/translation.zip)
> 
> 
> 
> 

Thanks for the improvement!

**Pull request merged**
