### PR TITLE
Add openapi API documentation

### PR DESCRIPTION
**Pull request by cocool97**
The goal of this PR is to add an OpenAPI documentation to the project.

This would allow us to have the documentation available at `/swagger/index.html` and not in the README.md file.

The only thing contributors have to do is keep API endpoint documentation accurate, and everything will be build to provide this new endpoint.

We could even automatically generate a JS + Kotlin API client if we want. 

- Add OpenAPI documentation generator
- Update README.md to remove endpoint documentations and make it cleaner

Endpoints to check :

**API** 

- [x] "/echo"
- [x] "/shutdown"
- [x] "/settings"
- [x] "/torrents"
- [x] "/torrent/upload"
- [ ] "/cache"
- [ ] "/stream"
- [ ] "/stream/*fname"
- [ ] "/stream"
- [ ] "/stream/*fname"
- [ ] "/play/:hash/:id"
- [ ] "/play/:hash/:id"
- [ ] "/viewed"
- [ ] "/playlistall/all.m3u"
- [ ] "/playlist"
- [ ] "/playlist/*fname"    -> Is this endpoint still needed as param `fname` is never used in endpoint handler ?
- [ ] "/download/:size"
- [ ] "/search/*query"
- [ ] "/ffp/:hash/:id"

**MSX**
 
- [ ] "/msx/:pth"
- [ ] "/msx/imdb"
- [ ] "/msx/imdb/:id"

**PAGES**

- [ ] "/stat"
- [ ] "/magnets"

Related to #49

### CODE REVIEW

**Comment by cocool97** [comment]
Ready for review ! @tsynik

**Comment by tsynik** [comment]
> ready for review ! @tsynik

added fname handle to stream and playlist functions. also some comments above

**Comment by tsynik** [comment]
Tried this a little: download api docs produces wrong url request
download
It must be as /download/10 etc. size is not a query key but url param

Also, there is no valid action values example for functions like /settings ("get"|"set") etc

**Comment by cocool97** [comment]
I'll double check all endpoints for issues like this one !

For the "get/set" params, as they are strings, I do not think that there is a way to specify variants. Either we set a comment for these actions, or we make one endpoint by action (this is more Rest-ful, but will introduce breaking changes...).

**Comment by shadeov** [comment]
@cocool97 also look at my PR https://github.com/cocool97/TorrServer/pull/1

**Comment by cocool97** [comment]
I'll check this for every endpoint 👍🏻 
* Clear, accurate and comprehensive documentation
* Endpoint testable through Swagger UI 

Endpoint checked on PR's first comment can be testes @tsynik. If you find issue(s) let me know this'll be an error.

**Pull request merged**
